// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqrHtFKsd2pKwqrWM1kgC-YqG2fScEzeg',
    appId: '1:442369987078:web:1b8db01ab40ba4ef8fe987',
    messagingSenderId: '442369987078',
    projectId: 'fooddeliveryapp-81f54',
    authDomain: 'fooddeliveryapp-81f54.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-81f54.firebasestorage.app',
    measurementId: 'G-RKZ0N6RE4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb4id4AmKkXsyB9D3FCIa7eaX5EChTe4U',
    appId: '1:442369987078:android:a45a0cb0e1db23f88fe987',
    messagingSenderId: '442369987078',
    projectId: 'fooddeliveryapp-81f54',
    storageBucket: 'fooddeliveryapp-81f54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT8dgYdV3TnAx2DmjRc9AWeuqO-o_OOuE',
    appId: '1:442369987078:ios:9e14cbc7a899b2298fe987',
    messagingSenderId: '442369987078',
    projectId: 'fooddeliveryapp-81f54',
    storageBucket: 'fooddeliveryapp-81f54.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT8dgYdV3TnAx2DmjRc9AWeuqO-o_OOuE',
    appId: '1:442369987078:ios:9e14cbc7a899b2298fe987',
    messagingSenderId: '442369987078',
    projectId: 'fooddeliveryapp-81f54',
    storageBucket: 'fooddeliveryapp-81f54.firebasestorage.app',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqrHtFKsd2pKwqrWM1kgC-YqG2fScEzeg',
    appId: '1:442369987078:web:83480de83969ba3f8fe987',
    messagingSenderId: '442369987078',
    projectId: 'fooddeliveryapp-81f54',
    authDomain: 'fooddeliveryapp-81f54.firebaseapp.com',
    storageBucket: 'fooddeliveryapp-81f54.firebasestorage.app',
    measurementId: 'G-WL31WZN8J0',
  );
}
